/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
export type { GameCharacterNFT } from "./GameCharacterNFT";
export type { GameThemeNFT } from "./GameThemeNFT";
